version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: WalletTeste
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=walletdb;Username=WalletTeste;Password=123456
      Jwt__Key: chave-secreta-super-forte
      Jwt__Issuer: WalletApi
      Jwt__Audience: WalletApiUser
    ports:
      - "5000:5000"

volumes:
  postgres_data: